### PR TITLE
Lazy load

### PR DESCRIPTION
**Pull request by kylekatarnls**
This feature should provide a sensible page load improvement in production environment but this should probably first be reviewed deeply and tagged as a 1.6 beta.

The principle is to load Pug stuff as late as possible, so if the cache did not expire, we won't load it at all and immediately let Laravel load the cached file.

### CODE REVIEW

**Comment by kylekatarnls** [comment]
Note: I will add more unit tests to fulfill the coverage before it should be merged.

**Comment by kylekatarnls** [comment]
Hi @weotch, do you have some time to test this?

**Comment by weotch** [comment]
Not _really_ but I'm fine w/ you releasing as is.  You sure seem to have covered yourself from  testing standpoint.

**Comment by kylekatarnls** [comment]
I'm using it in 2 projects and get no side effects. Only speed-up. So I'll merge it.

**Pull request merged**
